export const ALL_US_STATES = [
  { name: "Alabama", code: "AL", taxType: "progressive" },
  { name: "Alaska", code: "AK", taxType: "none" },
  { name: "Arizona", code: "AZ", taxType: "flat" },
  { name: "Arkansas", code: "AR", taxType: "progressive" },
  { name: "California", code: "CA", taxType: "progressive" },
  { name: "Colorado", code: "CO", taxType: "flat" },
  { name: "Connecticut", code: "CT", taxType: "progressive" },
  { name: "Delaware", code: "DE", taxType: "progressive" },
  { name: "Florida", code: "FL", taxType: "none" },
  { name: "Georgia", code: "GA", taxType: "progressive" },
  { name: "Hawaii", code: "HI", taxType: "progressive" },
  { name: "Idaho", code: "ID", taxType: "flat" },
  { name: "Illinois", code: "IL", taxType: "flat" },
  { name: "Indiana", code: "IN", taxType: "flat" },
  { name: "Iowa", code: "IA", taxType: "progressive" },
  { name: "Kansas", code: "KS", taxType: "progressive" },
  { name: "Kentucky", code: "KY", taxType: "flat" },
  { name: "Louisiana", code: "LA", taxType: "progressive" },
  { name: "Maine", code: "ME", taxType: "progressive" },
  { name: "Maryland", code: "MD", taxType: "progressive" },
  { name: "Massachusetts", code: "MA", taxType: "flat" },
  { name: "Michigan", code: "MI", taxType: "flat" },
  { name: "Minnesota", code: "MN", taxType: "progressive" },
  { name: "Mississippi", code: "MS", taxType: "flat" },
  { name: "Missouri", code: "MO", taxType: "progressive" },
  { name: "Montana", code: "MT", taxType: "progressive" },
  { name: "Nebraska", code: "NE", taxType: "progressive" },
  { name: "Nevada", code: "NV", taxType: "none" },
  { name: "New Hampshire", code: "NH", taxType: "none" },
  { name: "New Jersey", code: "NJ", taxType: "progressive" },
  { name: "New Mexico", code: "NM", taxType: "progressive" },
  { name: "New York", code: "NY", taxType: "progressive" },
  { name: "North Carolina", code: "NC", taxType: "flat" },
  { name: "North Dakota", code: "ND", taxType: "progressive" },
  { name: "Ohio", code: "OH", taxType: "progressive" },
  { name: "Oklahoma", code: "OK", taxType: "progressive" },
  { name: "Oregon", code: "OR", taxType: "progressive" },
  { name: "Pennsylvania", code: "PA", taxType: "flat" },
  { name: "Rhode Island", code: "RI", taxType: "progressive" },
  { name: "South Carolina", code: "SC", taxType: "progressive" },
  { name: "South Dakota", code: "SD", taxType: "none" },
  { name: "Tennessee", code: "TN", taxType: "none" },
  { name: "Texas", code: "TX", taxType: "none" },
  { name: "Utah", code: "UT", taxType: "flat" },
  { name: "Vermont", code: "VT", taxType: "progressive" },
  { name: "Virginia", code: "VA", taxType: "progressive" },
  { name: "Washington", code: "WA", taxType: "none" },
  { name: "West Virginia", code: "WV", taxType: "progressive" },
  { name: "Wisconsin", code: "WI", taxType: "progressive" },
  { name: "Wyoming", code: "WY", taxType: "none" },
  { name: "District of Columbia", code: "DC", taxType: "progressive" },
];